#! /usr/bin/env python3
"""Private application command interface."""

from appcmd.config import CONFIG
from appcmd.wsgi import PRIVATE


if __name__ == '__main__':
    HOST = CONFIG['private']['host']
    PORT = int(CONFIG['private']['port'])
    PRIVATE.run(host=HOST, port=PORT)
