#! /usr/bin/env python3
"""Public application command interface."""

from appcmd.config import CONFIG
from appcmd.wsgi import PUBLIC


if __name__ == '__main__':
    HOST = CONFIG['public']['host']
    PORT = int(CONFIG['public']['port'])
    PUBLIC.run(host=HOST, port=PORT)
